<?php

declare(strict_types=1);

// Arrays call a controller action. Strings display a read-only demo screen.
return [
    'GET' => [
        '/items'           => ['ItemController', 'index'],
        '/items/browse'    => ['ItemController', 'browse'],
        '/items/create'    => ['ItemController', 'createForm'],
        '/items/{id}'      => ['ItemController', 'show'],
        '/items/{id}/edit' => ['ItemController', 'editForm'],
        '/'                        => 'dashboard/index',
        '/dashboard'               => 'dashboard/index',
        '/bookings'                => ['BookingController', 'index'],
        '/bookings/{id}'           => ['BookingController', 'show'],
        '/wallet'                  => 'wallet/index',
        '/gifts'                   => 'gifts/index',
        '/gifts/new'               => 'gifts/index',
        '/notifications'           => 'notifications/index',
        '/help'                    => 'help/index',
        '/settings'                => 'settings/index',
        '/settings/close-account'  => 'settings/index',
        '/transparency'            => 'transparency/index',
        '/ratings'                 => 'ratings/index',
        '/trust'                   => 'trust/index',
        '/profile'                 => ['ProfileController', 'editForm'],
        '/members/{id}'            => ['ProfileController', 'show'],
        '/aid-grants'              => 'aid-grants/show',
        '/aid-grants/create'       => 'aid-grants/create',
        '/aid-grants/{id}'         => 'aid-grants/show',
        '/donations/{id}'          => 'donations/index',
        '/donations/{id}/handover' => 'donations/handover',
        '/community/temporary'     => 'community/create',
    
        // ── Admin ──
        '/admin'                          => 'admin/dashboard/index',
        '/admin/dashboard'                => 'admin/dashboard/index',
        '/admin/divisions'                => 'admin/divisions/index',
        '/admin/divisions/{id}'           => 'admin/divisions/show',
        '/admin/divisions/{id}/approvals' => 'admin/divisions/approvals',
        '/admin/moderators'               => 'admin/moderators/index',
        '/admin/moderators/performance'   => 'admin/moderators/performance',
        '/admin/moderators/appoint/{id}'  => 'admin/moderators/appoint',
        '/admin/moderators/appoint'       => 'admin/moderators/appoint',
        '/admin/moderators/objections/{id}' => 'admin/moderators/objections',
        '/admin/moderators/{id}'          => 'admin/moderators/show',
        '/admin/disputes'                 => 'admin/disputes/index',
        '/admin/disputes/{id}'            => 'admin/disputes/show',
        '/admin/disaster'                 => 'admin/disaster/index',
        '/admin/categories'               => 'admin/categories/index',
        '/admin/pools'                    => 'admin/pools/index',
        '/admin/pools/writeoffs'          => 'admin/pools/writeoffs',
        '/admin/pools/sponsor-ledger'     => 'admin/pools/sponsor-ledger',
        '/admin/pools/policies'           => 'admin/pools/policies',
        '/admin/ledger'                   => 'admin/ledger/index',
        '/admin/users'                    => 'admin/users/index',
        '/admin/users/{id}'               => 'admin/users/show',
        '/admin/cron'                     => 'admin/cron/index',
        '/admin/notifications'            => 'admin/notifications/index',
        '/admin/settings'                 => 'admin/settings/profile',
        '/admin/settings/profile'         => 'admin/settings/profile',
        '/admin/settings/security'        => 'admin/settings/security',
        '/admin/settings/notifications'   => 'admin/settings/notifications',
    
        // ── Moderator ──
        '/moderator'                         => 'moderator/dashboard/index',
        '/moderator/dashboard'               => 'moderator/dashboard/index',
        '/moderator/verifications'           => 'moderator/verifications/index',
        '/moderator/verifications/{id}'      => 'moderator/verifications/show',
        '/moderator/listing-approvals'       => 'moderator/listing-approvals/index',
        '/moderator/listing-approvals/{id}'  => 'moderator/listing-approvals/show',
        '/moderator/cases'                   => 'moderator/cases/index',
        '/moderator/cases/{id}'              => 'moderator/cases/show',
        '/moderator/disasters'               => 'moderator/disasters/index',
        '/moderator/aid-vouching'            => 'moderator/aid-vouching/index',
    
        // ── Sponsor Liaison ──
        '/sponsor-liaison'                       => 'sponsor-liaison/dashboard/index',
        '/sponsor-liaison/dashboard'             => 'sponsor-liaison/dashboard/index',
        '/sponsor-liaison/sponsors'              => ['SponsorLiaisonController', 'sponsors'],
        '/sponsor-liaison/sponsors/{id}'         => ['SponsorLiaisonController', 'sponsor'],
        '/sponsor-liaison/sponsors/onboarding'   => 'sponsor-liaison/sponsors/onboarding',
        '/sponsor-liaison/purchases'             => ['SponsorLiaisonController', 'purchases'],
        '/sponsor-liaison/purchases/{id}'        => ['SponsorLiaisonController', 'purchase'],
        '/sponsor-liaison/purchases/create'      => 'sponsor-liaison/purchases/create',
        '/sponsor-liaison/points-pool'           => 'sponsor-liaison/points-pool/index',
        '/sponsor-liaison/disasters'             => 'sponsor-liaison/disasters/index',
        '/sponsor-liaison/disasters/connection'  => 'sponsor-liaison/disasters/connection',
        '/sponsor-liaison/aid-grants'            => ['SponsorLiaisonController', 'grants'],
        '/sponsor-liaison/aid-grants/export'     => ['SponsorLiaisonController', 'exportGrants'],
        '/sponsor-liaison/aid-grants/{id}'       => ['SponsorLiaisonController', 'grant'],
        '/sponsor-liaison/csr-reports'           => 'sponsor-liaison/csr-reports/index',
        '/sponsor-liaison/csr-reports/quarterly' => 'sponsor-liaison/csr-reports/quarterly',
    
        // ── Sponsor ──
        '/sponsor'                 => 'sponsor/dashboard/index',
        '/sponsor/dashboard'       => 'sponsor/dashboard/index',
        '/sponsor/purchase-points' => 'sponsor/purchase-points/create',
        '/sponsor/csr-reports'     => 'sponsor/csr-reports/index',
        '/sponsor/branding'        => 'sponsor/branding/edit',
        '/sponsor/notifications'   => 'sponsor/notifications/index',
        '/sponsor/disasters/{id}'  => 'sponsor/disasters/show',
    ],
    'POST' => [
        '/items'              => ['ItemController', 'store'],
        '/items/{id}'         => ['ItemController', 'update'],
        '/items/{id}/archive' => ['ItemController', 'archive'],
        '/items/{id}/pause'   => ['ItemController', 'pause'],
        '/items/{id}/resume'  => ['ItemController', 'resume'],
    ],
];
