<?php

declare(strict_types=1);

// Arrays call a controller action. Strings display a read-only demo screen.
//
// ROLES is the role-action matrix (Plan §20.1 module 1.5, Rules/CONVENTIONS.md
// §7.4): the roles allowed under each path prefix. The longest matching prefix
// wins, '*' means any signed-in account, and a path no prefix covers is refused
// (fail closed). RbacMiddleware enforces it before any controller runs.
return [
    'ROLES' => [
        // Every member screen. A moderator is a verified member too (§16.3).
        '/'                => ['member', 'moderator'],
        '/transparency'    => ['*'],
        '/help'            => ['*'],
        '/notifications'   => ['*'],
        '/login'           => ['*'],
        '/register'        => ['*'],
        '/logout'          => ['*'],
        '/forgot-password' => ['*'],
        '/reset-password'  => ['*'],
        '/account'         => ['*'],
        '/admin'           => ['admin'],
        '/moderator'       => ['moderator'],
        '/sponsor-liaison' => ['sponsor_liaison'],
        '/sponsor'         => ['sponsor'],
    ],
    'GET' => [
        '/login'           => ['AuthController', 'loginForm'],
        '/register'        => ['AuthController', 'registerForm'],
        '/forgot-password'      => ['AuthController', 'forgotForm'],
        '/reset-password'       => ['AuthController', 'resetForm'],
        '/reset-password/code'  => ['AuthController', 'codeForm'],
        '/account/password'     => ['AccountController', 'passwordForm'],
        '/items'           => ['ItemController', 'index'],
        '/items/browse'    => ['ItemController', 'browse'],
        '/items/create'    => ['ItemController', 'createForm'],
        '/items/{id}'      => ['ItemController', 'show'],
        '/items/{id}/edit' => ['ItemController', 'editForm'],
        '/'                        => 'dashboard/index',
        '/dashboard'               => 'dashboard/index',
        '/bookings'                => ['BookingController', 'index'],
        '/bookings/{id}'           => ['BookingController', 'show'],
        '/wallet'                  => 'wallet/index',
        '/gifts'                   => 'gifts/index',
        '/gifts/new'               => 'gifts/index',
        '/notifications'           => 'notifications/index',
        '/help'                    => 'help/index',
        '/settings'                => ['AccountController', 'settings'],
        '/settings/close-account'  => ['AccountController', 'settings'],
        '/transparency'            => 'transparency/index',
        '/ratings'                 => 'ratings/index',
        '/trust'                   => 'trust/index',
        '/profile'                 => ['ProfileController', 'editForm'],
        '/members/{id}'            => ['ProfileController', 'show'],
        '/aid-grants'              => 'aid-grants/show',
        '/aid-grants/create'       => 'aid-grants/create',
        '/aid-grants/{id}'         => 'aid-grants/show',
        '/donations/{id}'          => 'donations/index',
        '/donations/{id}/handover' => 'donations/handover',
        '/community/temporary'     => 'community/create',
    
        // ── Admin ──
        '/admin'                          => 'admin/dashboard/index',
        '/admin/dashboard'                => 'admin/dashboard/index',
        '/admin/divisions'                => 'admin/divisions/index',
        '/admin/divisions/{id}'           => 'admin/divisions/show',
        '/admin/divisions/{id}/approvals' => 'admin/divisions/approvals',
        '/admin/moderators'               => 'admin/moderators/index',
        '/admin/moderators/performance'   => 'admin/moderators/performance',
        '/admin/moderators/appoint/{id}'  => 'admin/moderators/appoint',
        '/admin/moderators/appoint'       => 'admin/moderators/appoint',
        '/admin/moderators/objections/{id}' => 'admin/moderators/objections',
        '/admin/moderators/{id}'          => 'admin/moderators/show',
        '/admin/disputes'                 => 'admin/disputes/index',
        '/admin/disputes/{id}'            => 'admin/disputes/show',
        '/admin/disaster'                 => 'admin/disaster/index',
        '/admin/categories'               => 'admin/categories/index',
        '/admin/pools'                    => 'admin/pools/index',
        '/admin/pools/reserve'            => 'admin/pools/reserve',
        '/admin/listing-approvals'        => ['ListingApprovalController', 'index'],
        '/admin/listing-approvals/{id}'   => ['ListingApprovalController', 'show'],
        '/admin/pools/sponsor-ledger'     => 'admin/pools/sponsor-ledger',
        '/admin/pools/policies'           => 'admin/pools/policies',
        '/admin/ledger'                   => 'admin/ledger/index',
        '/admin/users'                    => 'admin/users/index',
        '/admin/users/{id}'               => 'admin/users/show',
        '/admin/cron'                     => 'admin/cron/index',
        '/admin/notifications'            => 'admin/notifications/index',
        '/admin/settings'                 => 'admin/settings/profile',
        '/admin/settings/profile'         => 'admin/settings/profile',
        '/admin/settings/security'        => 'admin/settings/security',
        '/admin/reset-codes'              => ['AccountSupportController', 'resetCodeForm'],
        '/admin/settings/notifications'   => 'admin/settings/notifications',
    
        // ── Moderator ──
        '/moderator'                         => 'moderator/dashboard/index',
        '/moderator/dashboard'               => 'moderator/dashboard/index',
        '/moderator/verifications'           => ['ModerationController', 'index'],
        '/moderator/verifications/{id}'      => ['ModerationController', 'show'],
        '/moderator/listing-approvals'       => ['ListingApprovalController', 'index'],
        '/moderator/listing-approvals/{id}'  => ['ListingApprovalController', 'show'],
        '/moderator/cases'                   => 'moderator/cases/index',
        '/moderator/cases/{id}'              => 'moderator/cases/show',
        '/moderator/disasters'               => 'moderator/disasters/index',
        '/moderator/aid-vouching'            => 'moderator/aid-vouching/index',
        '/moderator/address-changes'         => ['AccountSupportController', 'addressChanges'],
        '/moderator/reset-codes'             => ['AccountSupportController', 'resetCodeForm'],
    
        // ── Sponsor Liaison ──
        '/sponsor-liaison'                       => 'sponsor-liaison/dashboard/index',
        '/sponsor-liaison/dashboard'             => 'sponsor-liaison/dashboard/index',
        '/sponsor-liaison/sponsors'              => ['SponsorLiaisonController', 'sponsors'],
        '/sponsor-liaison/sponsors/{id}'         => ['SponsorLiaisonController', 'sponsor'],
        '/sponsor-liaison/sponsors/onboarding'   => 'sponsor-liaison/sponsors/onboarding',
        '/sponsor-liaison/purchases'             => ['SponsorLiaisonController', 'purchases'],
        '/sponsor-liaison/purchases/{id}'        => ['SponsorLiaisonController', 'purchase'],
        '/sponsor-liaison/purchases/create'      => 'sponsor-liaison/purchases/create',
        '/sponsor-liaison/points-pool'           => 'sponsor-liaison/points-pool/index',
        '/sponsor-liaison/disasters'             => 'sponsor-liaison/disasters/index',
        '/sponsor-liaison/disasters/connection'  => 'sponsor-liaison/disasters/connection',
        '/sponsor-liaison/aid-grants'            => ['SponsorLiaisonController', 'grants'],
        '/sponsor-liaison/aid-grants/export'     => ['SponsorLiaisonController', 'exportGrants'],
        '/sponsor-liaison/aid-grants/{id}'       => ['SponsorLiaisonController', 'grant'],
        '/sponsor-liaison/csr-reports'           => 'sponsor-liaison/csr-reports/index',
        '/sponsor-liaison/csr-reports/quarterly' => 'sponsor-liaison/csr-reports/quarterly',
    
        // ── Sponsor ──
        '/sponsor'                 => 'sponsor/dashboard/index',
        '/sponsor/dashboard'       => 'sponsor/dashboard/index',
        '/sponsor/purchase-points' => 'sponsor/purchase-points/create',
        '/sponsor/csr-reports'     => 'sponsor/csr-reports/index',
        '/sponsor/branding'        => 'sponsor/branding/edit',
        '/sponsor/notifications'   => 'sponsor/notifications/index',
        '/sponsor/disasters/{id}'  => 'sponsor/disasters/show',
    ],
    'POST' => [
        '/login'              => ['AuthController', 'login'],
        '/register'           => ['AuthController', 'register'],
        '/logout'             => ['AuthController', 'logout'],
        '/forgot-password'     => ['AuthController', 'forgot'],
        '/reset-password'      => ['AuthController', 'reset'],
        '/reset-password/code' => ['AuthController', 'resetWithCode'],
        '/account/password'    => ['AccountController', 'changePassword'],
        '/settings/preferences'   => ['AccountController', 'savePreferences'],
        '/settings/close-account' => ['AccountController', 'closeAccount'],
        '/profile'             => ['ProfileController', 'update'],
        '/profile/address'     => ['ProfileController', 'requestAddressChange'],
        '/moderator/address-changes/{id}/approve' => ['AccountSupportController', 'approveAddress'],
        '/moderator/address-changes/{id}/reject'  => ['AccountSupportController', 'rejectAddress'],
        '/moderator/reset-codes' => ['AccountSupportController', 'issueResetCode'],
        '/admin/reset-codes'     => ['AccountSupportController', 'issueResetCode'],
        '/admin/divisions'    => ['AdminController', 'createDivision'],
        '/admin/divisions/{id}'          => ['AdminController', 'updateDivision'],
        '/admin/divisions/{id}/archive'  => ['AdminController', 'archiveDivision'],
        '/moderator/verifications/{id}/approve' => ['ModerationController', 'approve'],
        '/moderator/verifications/{id}/reject'  => ['ModerationController', 'reject'],
        '/moderator/listing-approvals/{id}'     => ['ListingApprovalController', 'decide'],
        '/admin/listing-approvals/{id}'         => ['ListingApprovalController', 'decide'],
        '/items'              => ['ItemController', 'store'],
        '/items/{id}'         => ['ItemController', 'update'],
        '/items/{id}/archive' => ['ItemController', 'archive'],
        '/items/{id}/pause'   => ['ItemController', 'pause'],
        '/items/{id}/resume'  => ['ItemController', 'resume'],
    ],
];
